### PR TITLE
Resolve https://github.com/Bioconductor/BiocCheck/issues/84

### PR DESCRIPTION
**Pull request by lcolladotor**
This commit adds a GitHub Action workflow based on biocthis (version https://github.com/lcolladotor/biocthis/commit/02e69e84d0d516e245987b5643778029a6974f0a) that will run on the Bioconductor docker (devel or release depending on the branch) and show the output of `BiocGenerics:::testPackage()`.

### CODE REVIEW

**Comment by lcolladotor** [comment]
Related links:

**Comment by mtmorgan** [comment]
This seems to add a github action to BiocCheck itself. We will not implement that feature, because it introduces complicated dependencies on the continuous integration system used by Github actions -- we really want the core packages to be as simple as possible, so that any team member can maintain them.

I think biocthis would be a great location for a template like this; perhaps it would be appropriate to add a short paragraph to the BiocCheck vignette indicating that this is a possibility? The template itself would be maintained in biocthis.

**Comment by lcolladotor** [comment]
Hi,

The goal of this PR was to have GitHub run R CMD build and check for all the PRs we are submitting as part of the BiocCheck-a-thon (it would only really work if this PR was merged before other PRs were even submitted). That is, this is not an example/template GHA workflow for others to use, like you've said, `biocthis` already has a template and that's the main reason why I created `biocthis` in the first place.

Now, I do acknowledge that having any GHA workflow will expose maintainers to changes in dependencies for the workflow to work. However, that doesn't break any part of the actual R code and how it's built, etc. It's simply for helping contributors comply with the requested R CMD build/check on Bioc-devel (right now 3.12).

Like, `BiocCheck` is already on GitHub to enable forking and pull requests, so this is just a little bit of extra help in that direction.

See for example this PR at https://github.com/r-lib/actions/pull/101 which because that repo has a GHA workflow, the PR submission triggered 15 checks (their GHA workflow is long) that you can see at https://github.com/r-lib/actions/pull/101/checks.

Best,
Leo

**Comment by lshep** [comment]
I wouldn't be in favor of adding code simply for simplicity during the hackathon.

**Comment by lcolladotor** [comment]
Ok, no worries.

**Pull request closed without merging**
