### PR TITLE
bug fix: exit code when not interactive, closes #34

### LINKED ISSUE #34: BiocCheck exit code
Hi Martin and Lori, @mtmorgan @lshep 

I've integrated Travis-CI with `BiocCheck` but I'm still having issues getting an non-zero exit code
when running `BiocCheck` via `Rscript`:

```
git clone git@github.com:waldronlab/MultiAssayExperiment && cd MultiAssayExperiment
Rscript -e "BiocCheck::BiocCheck()"
```
the return code is 
```
$ echo $?
0
```
when it should be a `1`. 

The exit code works okay via `R CMD BiocCheck`. 

Regards,
Marcel

### PR DESCRIPTION
**Pull request by LiNk-NY**

### CODE REVIEW

**Comment by lshep** [comment]
This will cause BiocCheck to fail  on R CMD check because the example output will have ERROR's when running on the example package (which we want the test package to have some ERROR/WARNING/NOTES because we use the example packages in the tests) -  I assume in the example we would want to show ERROR/WARNING/NOTES too so users know what output to expect

**Comment by LiNk-NY** [comment]
There should be no errors in examples. My only solution would be to wrap the call with `dontrun`. 
Martin @mtmorgan thoughts?

**Comment by mtmorgan** [comment]
what about adding a new command line argument (these can also be used as args in `BiocCheck()`)?

```
--quit-with-status: ...
```

**Comment by LiNk-NY** [comment]
Hi Martin @mtmorgan & Lori @lshep ,
I've made the requested changes. Please see 21341d40fd5bcb8c4472b187b29aacccd9d01dbf.

**Pull request merged**
