### PR TITLE
Support site tags

### PR DESCRIPTION
**Pull request by lshep**
If you are submitting a pull request to `BiocCheck` please follow the instructions outlined in [this presentation](https://docs.google.com/presentation/d/1DkN2WVPOMVGqUtlSSrWbx6IMjtGP_cEHoE3nfOEnD68/edit#slide=id.p). This presentation includes steps for forking, creating a branch for you to work on, and useful related information.

Prior to sending the pull request, please verify that `R CMD build` and `R CMD check` run without warnings or errors on the latest Bioconductor-devel and complete the following steps:

* [X] Update the NEWS file (required)
* [X] Update the vignette file (required)
* [X] Add unit tests (optional)

The easiest way to obtain a working environment with Bioconductor-devel in your computer is to use the Bioconductor devel docker image as described in detail [in the Bioconductor website](https://www.bioconductor.org/help/docker/).

For more questions, please get in touch with the Bioconductor core team through the [Bioconductor Slack workspace](https://bioc-community.herokuapp.com/).

### CODE REVIEW

**Comment by lshep** [comment]
This will address #114 .   I made in an ERROR but maybe that is too strong. Maybe it should only be a warning?

**Comment by lshep** [comment]
@mtmorgan  @LiNk-NY @vjcitn    Any thoughts on adding this in?  And that it probably should be a warning not an error; maybe even just a note.   I'll want to rerun build/check again too to make sure everything has stayed the same with the api endpoint

**Comment by mtmorgan** [comment]
it's a little circular -- watching a tag for a package that doesn't yet exist -- but it seems like a step in the right direction so sounds good to me. Probably at the same level as 'are you subscribed to the support site?' which I think is an error?

**Review by LiNk-NY — APPROVED** [review]
@lshep This looks good to me! Thanks.

**Pull request merged**
