### PR TITLE
Avoid downloading external data, closes #75

### LINKED ISSUE #75: Error when downloading data from GitHub
https://raw.githubusercontent.com/
or other flagged external sources

### PR DESCRIPTION
**Pull request by LiNk-NY**
I've created a new PR because there was an issue with the merging `master` to the previous one. There are too many sources / changes in the master branch and I may have missed using `git merge -X master` and I am still not sure how to resolve the issues in the original `extdata` branch. 
This PR should only include my changes that are relevant to excluding download from external resources based on the current `master` branch. 

Update: I've added Dropbox to the list of excluded resources. 

Thanks!

### CODE REVIEW

**Comment by lshep** [comment]
This isn't picking up the dropbox reference in the package I'm reviewing -- AlpsNMR -- nor is it picking up github reference in leo's (since he complained about it in the open issue I used it as a test case against his github for recount).

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
Sorry about the silly mistakes. I've fixed them. 
Best,
Marcel

**Comment by lshep** [comment]
Sorry this took so long to get back to.  I tested with the above listed repos that are an example github and dropbox and it now seems to recognize okay.  I think we should rethink the file/line indication. For example using recount, The add_predication.R file actually references github in multiple locations but only one is listed: 
```
    * ERROR: Avoid references to external hosting platforms
      Found in files:
        add_predictions.R (line 75, column 13)
        coverage_matrix.R (line 95, column 31)
        expressed_regions.R (line 79, column 31)
```
Also @LiNk-NY / @mtmorgan  with the discussion on the community channels do we still want to keep this as an ERROR or should it only be a warning?

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
I've updated the PR to include the `github` keyword. I think it should still be an error because large data should be hosted on `ExperimentHub` or obtained from an instution's server via API, the [DataVerse](https://dataverse.harvard.edu/), etc.

**Pull request merged**
