### PR TITLE
not sure if this fixes issue with util.R/getDirFile -- but unit tests fail

### PR DESCRIPTION
**Pull request by vjcitn**
If you are submitting a pull request to `BiocCheck` please follow the
[instructions](https://docs.google.com/presentation/d/1DkN2WVPOMVGqUtlSSrWbx6IMjtGP_cEHoE3nfOEnD68/edit#slide=id.p).
The presentation includes steps for forking, creating a working branch, and
useful related information.

For a successful merge, the following steps are required:

* [x] Update the NEWS file
* [ ] Update the vignette file
* [ ] Add unit tests (optional but highly recommended)
* [ ] Passing `R CMD build` & `R CMD check` on Bioconductor devel

```
<bytecode: 0x145b39a50>
<environment: namespace:BiocCheck>
 --- function search by body ---
Function checkImportSuggestions in namespace BiocCheck has this body.
 ----------- END OF FAILURE REPORT -------------- 
Error in length(suggestions) && (!is.null(suggestions)) && (suggestions !=  : 
  'length(x) = 13 > 1' in coercion to 'logical(1)'
Calls: BiocCheck -> checkImportSuggestions
Execution halted
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running ‘runTests.R’
 ERROR
Running the tests in 'tests/runTests.R' failed.
Last 13 lines of output:
   
  1 Test Suite : 
  BiocCheck RUnit Tests - 44 test functions, 1 error, 0 failures
  ERROR in test_checkImportSuggestions: Error in length(suggestions) && (!is.null(suggestions)) && (suggestions !=  : 
    'length(x) = 17 > 1' in coercion to 'logical(1)'
  
  Test files with failing tests
  
     test_BiocCheck.R 
       test_checkImportSuggestions 
  
  
  Error in BiocGenerics:::testPackage("BiocCheck") : 
```

List a reviewer in the Pull Request (either @LiNk-NY, @lshep, @mtmorgan).
Reviewers will make sure to `Comment`, `Approve` or `Request changes`.

We _highly_ recommend the use of the Bioconductor devel docker image described
[on the Bioconductor website](https://www.bioconductor.org/help/docker/).

If you have any questions, please get in touch with the Bioconductor core team
on the [Bioconductor Community Slack](https://bioc-community.herokuapp.com/).

### CODE REVIEW

**Comment by LiNk-NY** [comment]
Hi Vince, @vjcitn 
Do you have the link to the package that triggers the error the PR is solving? I'd like to test with it. 
Thank you. 
-Marcel

**Comment by LiNk-NY** [comment]
BTW, it looks like the error is in `checkImportSuggestions`:

https://github.com/Bioconductor/BiocCheck/blob/efaddc14d6a45d2fee01c777a7c648b36e6543fc/R/checks.R#L552-L577

**Comment by vjcitn** [comment]
OK, I am back in business on this.  My patch does not solve the following, which occurs with the new submission cytoKernel:

```
* Checking for namespace import suggestions...
 ----------- FAILURE REPORT -------------- 
 --- failure: length > 1 in coercion to logical ---
 --- srcref --- 
: 
 --- package (from environment) --- 
BiocCheck
 --- call from context --- 
checkImportSuggestions(package_name)
 --- call from argument --- 
length(suggestions) && (!is.null(suggestions)) && (suggestions != 
    "ERROR")
 --- R stacktrace ---
where 1: checkImportSuggestions(package_name)
where 2: BiocCheck()

 --- value of length: 39 type: logical ---
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 --- function from context --- 
function (pkgname) 
{
    suggestions <- NULL
    tryCatch(suppressMessages(suppressWarnings({
        suggestions <- capture.output(codetoolsBioC::writeNamespaceImports(pkgname))
    })), error = function(e) {
        suggestions <- "ERROR"
        handleMessage("Could not get namespace suggestions.")
    })
    if (length(suggestions) && (!is.null(suggestions)) && (suggestions != 
        "ERROR")) {
        handleMessage("Namespace import suggestions are:")
        handleVerbatim(suggestions, indent = 4, exdent = 4, width = 1e+05)
        handleMessage("--END of namespace import suggestions.")
    }
    if ((!is.null(suggestions)) && (!length(suggestions))) {
        handleMessage("No suggestions.")
    }
    suggestions
}
<bytecode: 0x1559c3d60>
<environment: namespace:BiocCheck>
 --- function search by body ---
Function checkImportSuggestions in namespace BiocCheck has this body.
 ----------- END OF FAILURE REPORT -------------- 
Error in length(suggestions) && (!is.null(suggestions)) && (suggestions !=  : 
  'length(x) = 39 > 1' in coercion to 'logical(1)'

Enter a frame number, or 0 to exit  
```

**Comment by vjcitn** [comment]
Specifics: 
```
PC002284:cytoKernel vincentcarey$ git remote -v
origin	https://git.bioconductor.org/packages/cytoKernel (fetch)
origin	https://git.bioconductor.org/packages/cytoKernel (push)
PC002284:cytoKernel vincentcarey$ git log |head
commit 4bb128daa354b55611b187f85a85a947bc076d2d
Author: Tusharkanti Ghosh <44294394+tghosh30@users.noreply.github.com>
Date:   Sat Oct 2 08:34:07 2021 -0600

    Update README.md
```

**Comment by vjcitn** [comment]
```
> sessionInfo()
R version 4.1.1 Patched (2021-08-27 r80822)
Platform: aarch64-apple-darwin20.5.0 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
BLAS:   /Users/vincentcarey/R-4-1-dist/lib/R/lib/libRblas.dylib
LAPACK: /Users/vincentcarey/R-4-1-dist/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] BiocCheck_1.29.14           rlang_0.4.11               
 [3] magrittr_2.0.1              dplyr_1.0.7                
 [5] BiocParallel_1.27.10        data.table_1.14.2          
 [7] ashr_2.2-47                 circlize_0.4.13            
 [9] ComplexHeatmap_2.9.4        SummarizedExperiment_1.23.4
[11] Biobase_2.53.0              GenomicRanges_1.45.0       
[13] GenomeInfoDb_1.29.8         IRanges_2.27.2             
[15] S4Vectors_0.31.4            BiocGenerics_0.39.2        
[17] MatrixGenerics_1.5.4        matrixStats_0.61.0         
[19] Rcpp_1.0.7                  cytoKernel_0.99.0          
[21] rmarkdown_2.11             

loaded via a namespace (and not attached):
 [1] httr_1.4.2             foreach_1.5.1          assertthat_0.2.1      
 [4] highr_0.9              BiocManager_1.30.16    mixsqp_0.3-43         
 [7] RBGL_1.69.0            GenomeInfoDbData_1.2.7 pillar_1.6.3          
[10] lattice_0.20-45        glue_1.4.2             RUnit_0.4.32          
[13] digest_0.6.28          RColorBrewer_1.1-2     XVector_0.33.0        
[16] colorspace_2.0-2       htmltools_0.5.2        Matrix_1.3-4          
[19] XML_3.99-0.8           pkgconfig_2.0.3        GetoptLong_1.0.5      
[22] invgamma_1.1           zlibbioc_1.39.0        purrr_0.3.4           
[25] stringdist_0.9.8       getopt_1.20.3          optparse_1.6.6        
[28] tibble_3.1.4           biocViews_1.61.1       generics_0.1.0        
[31] ellipsis_0.3.2         crayon_1.4.1           evaluate_0.14         
[34] fansi_0.5.0            doParallel_1.0.16      truncnorm_1.0-8       
[37] graph_1.71.2           tools_4.1.1            GlobalOptions_0.1.2   
[40] lifecycle_1.0.1        cluster_2.1.2          DelayedArray_0.19.4   
[43] irlba_2.3.3            codetoolsBioC_0.1-0    compiler_4.1.1        
[46] RCurl_1.98-1.5         iterators_1.0.13       rjson_0.2.20          
[49] startup_0.15.0         bitops_1.0-7           codetools_0.2-18      
[52] DBI_1.1.1              R6_2.5.1               knitr_1.34            
[55] fastmap_1.1.0          utf8_1.2.2             clue_0.3-59           
[58] shape_1.4.6            parallel_4.1.1         SQUAREM_2021.1        
[61] vctrs_0.3.8            png_0.1-7              tidyselect_1.1.1      
[64] xfun_0.26             
        
```

**Comment by vjcitn** [comment]
I can't reproduce on Linux so I am closing this.

**Comment by LiNk-NY** [comment]
I can't reproduce the error either but the code in that function does not look right. I will see and update. 
Thanks !

**Pull request closed without merging**
